export default {
  LOAD_POKEMONS: 'LOAD_POKEMONS',
  LOAD_POKEMONS_ERROR: 'LOAD_POKEMONS_ERROR',
  LOAD_POKEMON: 'LOAD_POKEMON',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ADD_PRODUCT_CART: 'ADD_PRODUCT_CART',
  LOAD_CART: 'LOAD_CART'
};
